### PR TITLE
Bugfix: Fix empty space at bottom of SVG

### PR DESCRIPTION
**Pull request by jannikgohr**
Duolingo-Stats did not fill root SVG properly:
image

After this fix, it will now fit perfectly:
image

Fixing it was needed to properly apply box-shadows, etc. with CSS when embedding in a site.

### CODE REVIEW

**Comment by KevzPeter** [comment]
image

I had initially removed the ledge in Photoshop and converted it to an svg for the previous image, but the conversion process removed its feathers in the svg version for some reason. 

Could you update the viewbox for the new waving svg so that Duo stands at the same height as the language flags ?

**Comment by jannikgohr** [comment]
You are right, that ledge looks a bit weird.
I removed it and updated its position slightly.
image

Are you fine with the ledge in the other duo icons?
Or do you want me to remove them all to make it uniform?

**Comment by KevzPeter** [comment]
This looks great, and yeah, please remove the ledge from the other Duo icons too to keep it uniform

**Comment by jannikgohr** [comment]
Sorry, that was a bit messy on my part.
But now it should all look good!

The only thing left debatable is the size of the Duo icons.
They were all a bit differently sized in the SVG files, but I left it for now since it is a bit finicky to get it right.

**Pull request merged**
